name: Deploy AWS Lamda

on:
  push:
    branches: -main
    paths:
      - "lamda/"

jobs:
  deploy-lamda: # Name of the job
    runs-on: ubuntu-latest # Sets up the ga RUNNER
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python # Sets up python env
        uses: action/setup-python@v2
        with:
          pyhton-version: "3.12"

      - name: Install Dependencies # Installs any packages
        run: |
          pyhton -m pip install --upgrade pip
          pip install -r lamda/requirements.txt -t lamda

      - name: Configure AWS Credentials # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-acess-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-acess-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: eu-west-2

      - name: Deploy Lamda Function #zips lamda functtion and updats lamda functions
        run: |
          cd lamda
          zip -r lamda.zip
          aws lamda update-function-code --function-name my-test-cicd-lamda --zip-file fileb://lamda.zip
